# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="cloud"

plugins=(
    git
    zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh


alias zshconfig="mate ~/.zshrc"
alias ohmyzsh="mate ~/.oh-my-zsh"
alias github="cd /Users/mhussain/Desktop/code/github/mustafah15"
alias vimconf="nvim /Users/mhussain/Desktop/code/github/mustafah15/dotfiles"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
export PATH="/opt/homebrew/opt/php@7.4/bin:$PATH"


export PATH="/opt/homebrew/opt/php@8.2/bin:$PATH"
export PATH="/opt/homebrew/opt/php@8.2/sbin:$PATH"
export GOPATH="$HOME/go"
